name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'  # Sadece v ile baÅŸlayan tag'ler push edildiÄŸinde Ã§alÄ±ÅŸacak

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      # 1. AdÄ±m: Repository'yi checkout et
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Prepare Release Body
        id: prepare_release_body
        run: |
            BODY="## ğŸš€ Yeni SÃ¼rÃ¼m: v1.0.1
            ### DeÄŸiÅŸiklikler
            - Yeni Ã¶zellikler eklendi.
            - Hata dÃ¼zeltmeleri yapÄ±ldÄ±.
            - Performans iyileÅŸtirmeleri yapÄ±ldÄ±.

            ### KatkÄ±da Bulunanlar
            - @dtarim
            - @gtarim

            ### Detaylar
            Bu sÃ¼rÃ¼m, projenin stabilitesini artÄ±rmak iÃ§in birÃ§ok iyileÅŸtirme iÃ§erir."

            # TAG_NAME deÄŸiÅŸkenini iÃ§eriÄŸe ekleme
            RELEASE_BODY=$(echo "$BODY" | sed "s/\$TAG_NAME/${{ github.ref_name }}/g")

            # RELEASE_BODY'yi ortam deÄŸiÅŸkeni olarak ayarlama
            echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
            echo "$RELEASE_BODY" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

      - name: DENEMEEE
        id: deneme
        run: |
          echo "release body ${{env.RELEASE_BODY}}"

      # 3. AdÄ±m: GitHub Release oluÅŸtur
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # GitHub tarafÄ±ndan otomatik saÄŸlanan tag adÄ±
          name: Release ${{ github.ref_name }}  # Release adÄ±
          body: ${{env.RELEASE_BODY}}  # Åablon dosyasÄ±ndan okunan aÃ§Ä±klama
          draft: false  # Release'i draft olarak oluÅŸturma
          prerelease: false  # Release'i Ã¶n sÃ¼rÃ¼m (pre-release) olarak iÅŸaretleme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub tarafÄ±ndan otomatik saÄŸlanan token
